### ISSUE TITLE
career support - resumes - Build your Resume

### ISSUE THREAD

**Issue by ktrammell95** [philkrause/assignments#21]
Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary 
- [ ]  Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” simply use a headline that encapsulates your credentials.

## Skills 
- [ ]  You’ll want to incorporate the right keywords so that your resume is optimized for application tracking systems

## Professional experience
- [ ]  Focus on your accomplishments rather than your day-to-day responsibilities

## Education
- [ ]  Simply write where you went college and your degree.
- [ ]  It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ]  Volunteering and community service

## Due Date: Wednesday, June 19th
- [ ]  Upload or submit a link to your resume for review.

**Comment by philkrause** [comment]
[FullStackResume.pdf](https://github.com/philkrause/assignments/files/3303048/FullStackResume.pdf)

**Comment by ktrammell95** [comment]
Nice format and you have room to add more dev stuff that you are working on at SDG since you are already on 2 pages. Think about building that out a bit so you are pulling in those keywords that recruiters and hiring managers are looking for.

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Get up and dance!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3323b129c4533d8a45339c345692fab77f9771ac/meets-1.gif)
> &ldquo;Get up and dance!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/61)**__
