### ISSUE TITLE
week 08 - day 01 - explosive api

### ISSUE THREAD

**Issue by mdewey** [philkrause/assignments#30]
# Explosion Api

You have already solved the `explosion` and `mumbling` katas. The client loves your solution so much that they want you to turn it into an API us on the web.

For tonight, I want you to create a simple API with two endpoints, one for the `explosion` and one for the `mumbling`.

## Objectives

- Create a simple API
- Practice problem solving

## Requirements

- Install the `sdg-api` template using the command `dotnet new -i SDG.templates.Web.API`
- Create 2 endpoints, `/api/mumbling` and `api/explosion`, that are based off of the katas,`[https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling)` and `[https://www.codewars.com/kata/digits-explosion](https://www.codewars.com/kata/digits-explosion)` respectfully.

### Explorer Mode

- [ ] Create a new `sdg-web` api project
- [ ] Create a endpoint for the `mumbling` endpoint
  - [ ] Create a new Controller called `MumblingController`
  - [ ] This will have one `HttpGet`
  - [ ] The one get will accept a string
  - [ ] This endpoint will take the string passed to it, manipulate according to the kata [https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling) and return the result
  - [ ] This will return a `ActionResult<string>`
- [ ] Create a endpoint for the `explosion` endpoint
  - [ ] Create a new Controller called `ExplosionController`
  - [ ] This will have one `HttpGet`
  - [ ] The one get will accept a string
  - [ ] This endpoint will take the string passed to it, manipulate according to the kata [hhttps://www.codewars.com/kata/digits-explosion](hhttps://www.codewars.com/kata/digits-explosion) and return the result
  - [ ] This will return a `ActionResult<string>`
- [ ] turn in your project via github with a .gitignore.

### Adventure Mode

- [ ] Ensure your instructor has seen and approved your wireframes for your capstone.
- [ ] Work on the HTML for your capstone.
- [ ] Work on your Resume for Career Support.

**Comment by philkrause** [comment]
https://github.com/philkrause/kataAPI

**Comment by mdewey** [comment]
Your homework was marked: **Acceptable**

![A Gavin says "WAT?"](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBRdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0aa0c45fafab8f93fb0fab355476ce28550dbbf2/gavin.gif)
> &ldquo;A Gavin says "WAT?"&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/57)**__
