### ISSUE TITLE
week 03 - day 01  - js practice 

### ISSUE THREAD

**Issue by mdewey** [philkrause/assignments#9]
# JavaScript Iteration

Using JavaScript takes practice and the best practice is repetition. This exercise allow you time to work on the basics of JavaScript and how to apply that logic to solving problems.

## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of iteration/enumeration
- Further your black jack game

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/js-iteration) to your own account.
2. Change into your projects directory:
3. Clone your repository: `hub clone js-iteration`
4. Change into your project's directory: `cd js-iteration``
5. Install the dependencies: `yarn install` (or just `yarn` for short)
6. Open in your editor]
7. Start the test runner: `yarn test`
8. Open `src/functions.test.js` and work on functions until tests pass.
9. Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

## Explorer Mode

- Take a little time, (up to an hour or two) and work on your black game using the ideas we covered today in class
- Work on `js-iterations` using the directions above
- Finish the code and have all tests passing
- Have no linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Adventure Mode

- Do the same with the JavaScript Koans at [https://github.com/suncoast-devs/koans/blob/master/koans.js](https://github.com/suncoast-devs/koans/blob/master/koans.js)

- Do the same with the Function-Junction Koans at [https://github.com/suncoast-devs/function-junction](https://github.com/suncoast-devs/function-junction)

## Additional Resources

Reference the documentation on DevDocs to find what kind of helpful functions might already be in JavaScript.

- [String Functions on DevDocs](https://devdocs.io/javascript/global_objects/string).
- [Array Functions on DevDocs](http://devdocs.io/javascript/global_objects/array).

**Comment by philkrause** [comment]
https://github.com/philkrause/js-iteration

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe539f8c569aecbf6ed495afb3da8e6e3192b8b3/giphy-15.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/80)**__
